# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f24f7888d1e67f41cffb726af5e972f51c5bbc3be987c1880584f8950138eb83f3e79808fc972208bbd1163188371e49007ec73622b8c1f36449455908b64667

test:
  secret_key_base: 523156ce70e80e673fdd52bd25a7368241bd4859034d84058001ed870476175e66b24d2953ff5a42bab2a3118b78fe11fe784ee816bbeccaf405062d7e0a7859

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
